name: PlayerBiomes
authors: [ Ilamparithi ]
main: com.pseudosmp.PlayerBiomes.PlayerBiomes
version: ${project.version}
description: ${project.description}
api-version: "1.16"
commands:
  whatbiome:
    description: Displays the name of the biome the player is currently in.
    usage: /whatbiome
    permission: playerbiomes.command.whatbiome
    aliases: [whereami]
  playerbiomes:
    description: Reloads the configuration of PlayerBiomes.
    usage: /playerbiomes reload
    permission: playerbiomes.command.reload
    aliases: [pb]
permissions:
  playerbiomes.command.whatbiome:
    description: Allows usage of the /whatbiome command
    default: true
  playerbiomes.command.reload:
    description: Allows usage of the /playerbiomes reload command
    default: op
softdepend: [ PlaceholderAPI ]